name: Preprocessing Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download Dataset heart.csv ke root repo
      run: |
        curl -o heart.csv https://raw.githubusercontent.com/daffaakifah/Eksperimen_SML_Daffa-Akifah-Balqis/main/heart.csv

    - name: Setup Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run preprocessing script automate_daffabalqis.py
      run: |
        python preprocessing/automate_daffabalqis.py

    - name: Verify output heart_preprocessed.csv exists
      run: |
        echo "Listing files in preprocessing folder:"
        ls -l preprocessing/
        if [ -f preprocessing/heart_preprocessed.csv ]; then
          echo "File found! Showing first 5 lines:"
          head -n 5 preprocessing/heart_preprocessed.csv
        else
          echo "File preprocessing/heart_preprocessed.csv NOT FOUND!"
          exit 1
        fi

    - name: Prepare git config
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Add preprocessing output file, commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add -f preprocessing/heart_preprocessed.csv
        git status
        git commit -m "Add/update heart_preprocessed.csv after preprocessing" || echo "No changes to commit"
        # Push menggunakan PAT dengan format URL termasuk token
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/daffaakifah/Eksperimen_SML_Daffa-Akifah-Balqis.git HEAD:main
