name: Preprocessing Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Penting untuk operasi git berikutnya

      - name: Download Dataset
        run: |
          curl -o preprocessing/heart.csv "https://raw.githubusercontent.com/daffaakifah/Eksperimen_SML_Daffa-Akifah-Balqis/main/heart.csv"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        working-directory: ./preprocessing 
        run: |
          python automate_daffabalqis.py

      - name: Verify processed file
        run: |
          echo "Isi folder preprocessing:"
          ls -lh preprocessing/
          [ -f preprocessing/heart_preprocessed.csv ] || exit 1

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add preprocessing/
          git status
          git commit -m "Add preprocessed dataset" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
