name: Preprocessing Dataset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Dataset
        run: |
          mkdir -p preprocessing
          curl -o heart.csv "https://raw.githubusercontent.com/daffaakifah/Eksperimen_SML_Daffa-Akifah-Balqis/main/heart.csv"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          echo "Isi folder sebelum preprocessing:"
          ls -l preprocessing/
          python preprocessing/automate_daffabalqis.py
          echo "Isi folder setelah preprocessing:"
          ls -l preprocessing/

      - name: Verify processed file
        run: |
          echo "Isi folder preprocessing:"
          ls -lh preprocessing/
          if [ -f preprocessing/heart_preprocessed.csv ]; then
            echo "File ditemukan!"
            head -n 5 preprocessing/heart_preprocessed.csv
          else
            echo "ERROR: File heart_preprocessed.csv tidak ditemukan!"
            find . -name heart_preprocessed.csv
            exit 1
          fi

      - name: Show git status before adding file
        run: git status

      - name: Add preprocessed file forced (-f)
        run: git add -f preprocessing/heart_preprocessed.csv

      - name: Show git status after adding file
        run: git status

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -m "Add preprocessed heart dataset" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
